typography_spectrum: 0.9857714707031846
color:
  brandStrength: 0.47102626715786755
  lightness: 0.8259771270677447
  saturation: 0.4319875342771411
  rhythmicContrast: 0.7602548759896308
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.560619312338531
author:
  name: 'Stefan MHerzog. '
  url: ''
name: stefanherzog.org
navigation:
  - name: About
    id: defa31f7-ee85-46ba-942d-f9f5d7871edc
    type: content
title: Stefan M. Herzog
description: Improving judgment and decision making
