typography_spectrum: 0.018397361040115356
color:
  brandStrength: 0.5160663514398038
  lightness: 0.42706034472212195
  saturation: 0.8125412808731198
  rhythmicContrast: 0.042721277102828026
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.004775128094479442
author:
  name: Stefan Herzog
  url: 'http://stefanherzog.org'
name: stefanherzog.org
navigation:
  - name: About
    id: defa31f7-ee85-46ba-942d-f9f5d7871edc
    type: content
title: Stefan M. Herzog
description: Improving judgment and decision making
