typography_spectrum: 0.26990053919143975
color:
  brandStrength: 0.41223624045960605
  lightness: 0.6072204292286187
  saturation: 0.07819038396701217
  rhythmicContrast: 0.8612785425502807
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.5852594948373735
author:
  name: 'Stefan MHerzog. '
  url: ''
name: stefanherzog.org
navigation:
  - name: About
    id: defa31f7-ee85-46ba-942d-f9f5d7871edc
    type: content
title: Stefan M. Herzog
description: Improving judgment and decision making
