typography_spectrum: 0.7301949127577245
color:
  brandStrength: 0.5946084600873291
  lightness: 0.9198831112589687
  saturation: 0.5296377567574382
  rhythmicContrast: 0.5282854014076293
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.709295928478241
author:
  name: Stefan Herzog
  url: 'http://stefanherzog.org'
name: stefanherzog.org
navigation: []
title: Stefan M. Herzog
description: Improving judgment and decision making
